name: Python Tests

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  PYTHONPATH: "${{ github.workspace }}"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-rerunfailures

      - name: Install Playwright browsers
        run: playwright install

      - name: Run tests
        run: pytest tests -v

      - name: Run tests with xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' pytest tests -v
